'use client'

import React, { createContext, useContext, useState, useEffect, useMemo, useCallback } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Lazy load translations to reduce initial bundle size
const getTranslations = (lang: Language) => {
  if (lang === 'en') {
    return {
    // Navigation
    'nav.home': 'Home',
    'nav.doctors': 'Our Doctors',
    'nav.services': 'Services',
    'nav.appointments': 'Appointments',
    'nav.news': 'News & Updates',
    'nav.contact': 'Contact Us',
    "nav.messages": "Messages",
    "nav.inventory": "Inventory",
    "nav.patients": "Patients",
    "nav.billing": "Billing",
    "nav.activityLogs": "Activity Logs",

    // Header
    'header.title': 'Intergastro',
    'header.subtitle': 'Your Health Partner',
    'header.search.placeholder': 'Search doctors, services...',
    'header.language.en': 'Switch to Spanish',
    'header.language.es': 'Cambiar a Inglés',
    
    // Hero Section
    'hero.title': 'Your Health, Our Priority',
    'hero.subtitle': 'Providing exceptional medical care with compassion and expertise. Our team of experienced doctors is here to serve you and your family.',
    'hero.cta.primary': 'Schedule Appointment',
    'hero.cta.secondary': 'Learn More',
    
    // Doctors Section
    'doctors.title': 'Meet Our Expert Doctors',
    'doctors.subtitle': 'Our team of highly qualified medical professionals is dedicated to providing you with the best possible care.',
    'doctors.experience': 'experience',
    'doctors.book': 'Book Consultation',
    
    // Services Section
    'services.title': 'Our Medical Services',
    'services.subtitle': 'Comprehensive healthcare services tailored to meet your medical needs.',
    'services.general.title': 'General Consultation',
    'services.general.description': 'Comprehensive health checkups and routine medical care',
    'services.cardiology.title': 'Cardiology',
    'services.cardiology.description': 'Heart health assessments and cardiovascular treatments',
    'services.preventive.title': 'Preventive Care',
    'services.preventive.description': 'Vaccinations, screenings, and health maintenance',
    'services.emergency.title': 'Emergency Care',
    'services.emergency.description': '24/7 emergency medical services and urgent care',
    
    // News Section
    'news.title': 'Latest News & Updates',
    'news.subtitle': 'Stay informed with the latest medical insights and clinic updates from our doctors.',
    'news.readMore': 'Read More',
    
    // Contact Section
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with us for appointments, inquiries, or emergency care.',
    'contact.address.title': 'Address',
    'contact.address.value': 'Plaza Intermédica 3er Nivel,\n #309-C 3a Calle Poniente y 25 Avenida Norte,\n San Salvador',
    'contact.phone.title': 'Phone',
    'contact.phone.main': 'Main: (503) 7777-7777',
    'contact.phone.emergency': 'Emergency: 911',
    'contact.email.title': 'Email',
    'contact.email.general': 'General: info@intergastro.com',
    'contact.email.appointments': 'Appointments: appointments@intergastro.com',
    'contact.hours.title': 'Hours',
    'contact.hours.weekdays': 'Monday - Friday: 8:00 AM - 6:00 PM',
    'contact.hours.saturday': 'Saturday: 9:00 AM - 4:00 PM',
    'contact.hours.sunday': 'Sunday: Emergency Only',
    'contact.form.title': 'Send us a Message',
    'contact.form.firstName': 'First Name',
    'contact.form.lastName': 'Last Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone',
    'contact.form.message': 'Your message...',
    'contact.form.send': 'Send Message',
    
    // Footer
    'footer.copyright': '© 2024 Intergastro. All rights reserved. | Licensed Healthcare Provider',
    
    // Quick Contact
    'quick.contact.phone': '(503) 7777-7777',
    'quick.contact.email': 'info@intergastro.com',
    'quick.contact.hours': 'Mon-Fri: 8AM-6PM',

      // Settings
      'settings.title': 'Settings',
      'settings.subtitle': 'Manage clinic preferences and settings',
      'settings.sections.clinic': 'Clinic Profile',
      'settings.sections.users': 'Users & Roles',
      'settings.sections.schedule': 'Schedule & Hours',
      'settings.sections.billing': 'Billing & DTE',
      'settings.sections.notifications': 'Notifications',
      'settings.sections.security': 'Security',
      'settings.sections.integrations': 'Integrations',

      // Clinic Profile
      'settings.clinic.title': 'Clinic Profile',
      'settings.clinic.subtitle': 'Basic clinic information',
      'settings.clinic.general.title': 'General Information',
      'settings.clinic.general.description': 'Main clinic data',
      'settings.clinic.general.name': 'Clinic Name',
      'settings.clinic.general.namePlaceholder': 'San Rafael Medical Clinic',
      'settings.clinic.general.phone': 'Phone',
      'settings.clinic.general.phonePlaceholder': '+503 2234-5678',
      'settings.clinic.general.address': 'Address',
      'settings.clinic.general.addressPlaceholder': 'Main St. #123, San Salvador, El Salvador',
      'settings.clinic.general.email': 'Email',
      'settings.clinic.general.emailPlaceholder': 'info@clinicasanrafael.com',
      'settings.clinic.general.logo': 'Clinic Logo',
      'settings.clinic.general.uploadLogo': 'Upload Logo',
      'settings.clinic.general.specialties': 'Medical Specialties',
      'settings.clinic.general.specialty.general': 'General Medicine',
      'settings.clinic.general.specialty.cardiology': 'Cardiology',
      'settings.clinic.general.specialty.pediatrics': 'Pediatrics',
      'settings.clinic.general.addSpecialty': 'Add',
      'settings.clinic.general.language': 'Language',
      'settings.clinic.general.selectLanguage': 'Select language',
      'settings.clinic.general.language.es': 'Spanish',
      'settings.clinic.general.language.en': 'English',
      'settings.clinic.general.timezone': 'Timezone',
      'settings.clinic.general.selectTimezone': 'Select timezone',
      'settings.clinic.general.timezone.elSalvador': 'America/El Salvador (CST)',
      'settings.clinic.general.timezone.guatemala': 'America/Guatemala (CST)',
      'settings.clinic.saveChanges': 'Save Changes',

      // Users & Roles
      'settings.users.title': 'Users & Roles',
      'settings.users.subtitle': 'Manage users and their permissions',
      'settings.users.addUser': 'Add User',
      'settings.users.addUserDescription': 'Create a new user account with specific role and permissions',
      'settings.users.editUser.title': 'Edit User',
      'settings.users.editUser.description': 'Modify user information and role',
      'settings.users.editUser.save': 'Save Changes',
      'settings.users.passwordReset.title': 'Reset Password',
      'settings.users.passwordReset.description': 'Set a new password for',
      'settings.users.passwordReset.newPassword': 'New Password',
      'settings.users.passwordReset.reset': 'Reset Password',
      'settings.users.deleteUser.title': 'Delete User',
      'settings.users.deleteUser.description': 'Are you sure you want to delete',
      'settings.users.deleteUser.cancel': 'Cancel',
      'settings.users.deleteUser.confirm': 'Delete',
      'settings.users.lastLogin': 'Last Login',
      'settings.users.form.name': 'Name',
      'settings.users.form.email': 'Email',
      'settings.users.form.roles': 'Roles',
      'settings.users.form.selectRole': 'Select role',
      'settings.users.form.password': 'Password',
      'settings.users.form.status': 'Status',
      'settings.users.status.active': 'Active',
      'settings.users.status.inactive': 'Inactive',
      'settings.users.userList.title': 'User List',
      'settings.users.userList.description': 'Registered users in the system',
      'settings.users.userList.doctor1.name': 'Dr. Roberto Martínez',
      'settings.users.userList.doctor1.email': 'roberto@clinica.com',
      'settings.users.userList.doctor1.role': 'Administrator',
      'settings.users.userList.doctor2.name': 'Dr. María González',
      'settings.users.userList.doctor2.email': 'maria@clinica.com',
      'settings.users.userList.doctor2.role': 'Doctor',
      'settings.users.userList.secretary.name': 'Ana Rodríguez',
      'settings.users.userList.secretary.email': 'ana@clinica.com',
      'settings.users.userList.secretary.role': 'Secretary',
      'settings.users.roles.title': 'Role Configuration',
      'settings.users.roles.description': 'Define permissions for each role',
      'settings.users.roles.admin.title': 'Administrator',
      'settings.users.roles.admin.manageUsers': 'Manage users',
      'settings.users.roles.admin.billingAccess': 'Billing access',
      'settings.users.roles.admin.viewReports': 'View reports',
      'settings.users.roles.admin.settings': 'Settings',
      'settings.users.roles.doctor.title': 'Doctor',
      'settings.users.roles.doctor.managePatients': 'Manage patients',
      'settings.users.roles.doctor.viewAppointments': 'View appointments',
      'settings.users.roles.doctor.prescribeMedications': 'Prescribe medications',
      'settings.users.roles.doctor.viewMedicalReports': 'View medical reports',
      'settings.users.roles.secretary.title': 'Secretary',
      'settings.users.roles.secretary.viewPatients': 'View patients',
      'settings.users.roles.secretary.manageAppointments': 'Manage appointments',
      'settings.users.roles.secretary.viewBilling': 'View billing',
      'settings.users.roles.secretary.viewBasicReports': 'View basic reports',
      'settings.users.roles.secretary.phoneAccess': 'Phone access',
      'settings.users.roles.secretary.emailAccess': 'Email access',

      // Schedule
      'settings.schedule.title': 'Schedule & Hours',
      'settings.schedule.subtitle': 'Configure appointment schedules and hours',
      'settings.schedule.hours.title': 'Operating Hours',
      'settings.schedule.hours.description': 'Define hours by day of the week',
      'settings.schedule.hours.days.monday': 'Monday',
      'settings.schedule.hours.days.tuesday': 'Tuesday',
      'settings.schedule.hours.days.wednesday': 'Wednesday',
      'settings.schedule.hours.days.thursday': 'Thursday',
      'settings.schedule.hours.days.friday': 'Friday',
      'settings.schedule.hours.days.saturday': 'Saturday',
      'settings.schedule.hours.days.sunday': 'Sunday',
      'settings.schedule.hours.to': 'to',
      'settings.schedule.appointments.title': 'Appointment Configuration',
      'settings.schedule.appointments.description': 'Parameters for the appointment system',
      'settings.schedule.appointments.duration': 'Standard appointment duration',
      'settings.schedule.appointments.selectDuration': 'Select duration',
      'settings.schedule.appointments.duration.15min': '15 minutes',
      'settings.schedule.appointments.duration.30min': '30 minutes',
      'settings.schedule.appointments.duration.45min': '45 minutes',
      'settings.schedule.appointments.duration.1hour': '1 hour',
      'settings.schedule.appointments.bufferTime': 'Buffer time between appointments',
      'settings.schedule.appointments.selectBuffer': 'Select buffer',
      'settings.schedule.appointments.buffer.noBuffer': 'No buffer',
      'settings.schedule.appointments.buffer.5min': '5 minutes',
      'settings.schedule.appointments.buffer.10min': '10 minutes',
      'settings.schedule.appointments.buffer.15min': '15 minutes',
      'settings.schedule.appointments.holidays': 'Holidays and exceptions',
      'settings.schedule.appointments.holidays.newYear': 'January 1st - New Year',
      'settings.schedule.appointments.holidays.independence': 'September 15th - Independence',
      'settings.schedule.appointments.holidays.addHoliday': 'Add Holiday',

      // Billing
      'settings.billing.title': 'Billing & DTE',
      'settings.billing.subtitle': 'Fiscal and electronic billing configuration',
      'settings.billing.tax.title': 'Tax Data',
      'settings.billing.tax.description': 'Clinic tax information',
      'settings.billing.tax.nit': 'NIT',
      'settings.billing.tax.nitPlaceholder': '0614-123456-123-4',
      'settings.billing.tax.businessName': 'Business Name',
      'settings.billing.tax.businessNamePlaceholder': 'San Rafael Medical Clinic S.A. de C.V.',
      'settings.billing.tax.taxAddress': 'Tax Address',
      'settings.billing.tax.taxAddressPlaceholder': 'Address registered in NIT',
      'settings.billing.tax.currency': 'Currency',
      'settings.billing.tax.selectCurrency': 'Select currency',
      'settings.billing.tax.currency.usd': 'USD - US Dollar',
      'settings.billing.tax.currency.eur': 'EUR - Euro',
      'settings.billing.tax.vatRate': 'VAT Rate (%)',
      'settings.billing.dte.title': 'Electronic Billing (DTE)',
      'settings.billing.dte.description': 'Configuration for El Salvador DTE system',
      'settings.billing.dte.enable': 'Enable DTE',
      'settings.billing.dte.enableDescription': 'Activate electronic billing',
      'settings.billing.dte.environment': 'Environment',
      'settings.billing.dte.selectEnvironment': 'Select environment',
      'settings.billing.dte.environment.test': 'Test',
      'settings.billing.dte.environment.production': 'Production',
      'settings.billing.dte.invoiceSeries': 'Invoice Series',
      'settings.billing.dte.nextInvoiceNumber': 'Next Invoice Number',

      // Notifications
      'settings.notifications.title': 'Notifications',
      'settings.notifications.subtitle': 'Configure automatic notifications',
      'settings.notifications.email.title': 'Email Notifications',
      'settings.notifications.email.description': 'Automatic email configuration',
      'settings.notifications.email.confirmations': 'Appointment confirmations',
      'settings.notifications.email.confirmationsDescription': 'Send email when confirming appointments',
      'settings.notifications.email.reminders': 'Appointment reminders',
      'settings.notifications.email.remindersDescription': 'Reminder 24h before appointment',
      'settings.notifications.email.invoices': 'Issued invoices',
      'settings.notifications.email.invoicesDescription': 'Send invoice by email',
      'settings.notifications.sms.title': 'SMS Notifications',
      'settings.notifications.sms.description': 'Text message configuration',
      'settings.notifications.sms.reminders': 'SMS reminders',
      'settings.notifications.sms.remindersDescription': 'SMS 2 hours before appointment',
      'settings.notifications.sms.confirmations': 'SMS confirmations',
      'settings.notifications.sms.confirmationsDescription': 'SMS when scheduling appointment',
      'settings.notifications.templates.title': 'Message Templates',
      'settings.notifications.templates.description': 'Customize automatic messages',
      'settings.notifications.templates.reminder': 'Reminder Template',
      'settings.notifications.templates.reminderPlaceholder': 'Hello {name}, we remind you of your appointment on {date} at {time} at {clinic}.',
      'settings.notifications.templates.confirmation': 'Confirmation Template',
      'settings.notifications.templates.confirmationPlaceholder': 'Your appointment has been confirmed for {date} at {time}. Thank you for choosing {clinic}.',

      // Security
      'settings.security.title': 'Security',
      'settings.security.subtitle': 'Security and access configuration',
      'settings.security.password.title': 'Change Password',
      'settings.security.password.description': 'Update your access password',
      'settings.security.password.current': 'Current Password',
      'settings.security.password.new': 'New Password',
      'settings.security.password.confirm': 'Confirm New Password',
      'settings.security.password.change': 'Change Password',
      'settings.security.2fa.title': 'Two-Factor Authentication (2FA)',
      'settings.security.2fa.description': 'Add an extra layer of security',
      'settings.security.2fa.enable': 'Enable 2FA',
      'settings.security.2fa.enableDescription': 'Requires additional code when logging in',
      'settings.security.2fa.method': '2FA Method',
      'settings.security.2fa.selectMethod': 'Select method',
      'settings.security.2fa.method.sms': 'SMS',
      'settings.security.2fa.method.email': 'Email',
      'settings.security.2fa.method.app': 'Authenticator App',
      'settings.security.sessions.title': 'Active Sessions',
      'settings.security.sessions.description': 'Devices with active session',
      'settings.security.sessions.chromeWindows': 'Chrome on Windows',
      'settings.security.sessions.chromeWindowsDetails': 'IP: 192.168.1.100 • Last activity: 5 min ago',
      'settings.security.sessions.safariIphone': 'Safari on iPhone',
      'settings.security.sessions.safariIphoneDetails': 'IP: 192.168.1.105 • Last activity: 2 hours ago',
      'settings.security.sessions.current': 'Current',
      'settings.security.sessions.logout': 'Logout',
      'settings.security.sessions.logoutAll': 'Logout All Sessions',
      'settings.security.policies.title': 'Password Policies',
      'settings.security.policies.description': 'Requirements for user passwords',
      'settings.security.policies.minLength': 'Minimum length',
      'settings.security.policies.expiryDays': 'Expiry (days)',
      'settings.security.policies.requireUppercase': 'Require uppercase',
      'settings.security.policies.requireNumbers': 'Require numbers',
      'settings.security.policies.requireSymbols': 'Require symbols',

      // Integrations
      'settings.integrations.title': 'Integrations',
      'settings.integrations.subtitle': 'Connect with external systems',
      'settings.integrations.payments.title': 'Payments',
      'settings.integrations.payments.description': 'Online payment processors',
      'settings.integrations.payments.stripe.name': 'Stripe',
      'settings.integrations.payments.stripe.description': 'Card processing',
      'settings.integrations.payments.paypal.name': 'PayPal',
      'settings.integrations.payments.paypal.description': 'Digital payments',
      'settings.integrations.calendar.title': 'Calendar',
      'settings.integrations.calendar.description': 'Appointment synchronization',
      'settings.integrations.calendar.google.name': 'Google Calendar',
      'settings.integrations.calendar.google.description': 'Sync medical appointments',
      'settings.integrations.calendar.outlook.name': 'Outlook Calendar',
      'settings.integrations.calendar.outlook.description': 'Microsoft integration',
      'settings.integrations.laboratories.title': 'Laboratories',
      'settings.integrations.laboratories.description': 'Clinical laboratory systems',
      'settings.integrations.laboratories.labcorp.name': 'LabCorp',
      'settings.integrations.laboratories.labcorp.description': 'Laboratory results',
      'settings.integrations.ai.title': 'Artificial Intelligence',
      'settings.integrations.ai.description': 'Medical AI services',
      'settings.integrations.ai.transcription.name': 'AI Transcription',
      'settings.integrations.ai.transcription.description': 'Consultation transcription',
      'settings.integrations.ai.diagnosis.name': 'AI Diagnosis Assistant',
      'settings.integrations.ai.diagnosis.description': 'Diagnosis assistant',
      'settings.integrations.status.connected': 'Connected',
      'settings.integrations.status.disconnected': 'Disconnected',
      'settings.integrations.connect': 'Connect',
      'settings.integrations.configure': 'Configure',

      // Messages
      'messages.title': 'Contact Form Submissions',
      'messages.subtitle': 'Manage and review patient inquiries and contact requests',
      'messages.search.placeholder': 'Search by name, email, or message...',
      'messages.filter.all': 'All Messages',
      'messages.filter.new': 'New Only',
      'messages.filter.reviewed': 'Reviewed Only',
      'messages.status.new': 'New',
      'messages.status.reviewed': 'Reviewed',
      'messages.sections.new': 'New Messages',
      'messages.sections.reviewed': 'Reviewed Messages',
      'messages.actions.viewDetails': 'View Details',
      'messages.actions.markReviewed': 'Mark Reviewed',
      'messages.noResults': 'No messages found matching your criteria.',
      'messages.clearFilters': 'Clear Filters',
      'messages.modal.title': 'Message Details',
      'messages.modal.contact.email': 'Email:',
      'messages.modal.contact.phone': 'Phone:',
      'messages.modal.message': 'Message:',
      'messages.dateFormat.short': 'short',
      'messages.dateFormat.long': 'long',
      'messages.placeholder.noMessage': 'No message',
      'messages.placeholder.noEmail': 'No email',
      'messages.placeholder.noPhone': 'No phone',

      // Consultation Configuration
      'consultation.config.title': 'Consultation Configuration',
      'consultation.config.subtitle': 'Manage medical orders, medications, complaints, and symptoms',
      'consultation.config.sections.medicalOrders': 'Medical Orders',
      'consultation.config.sections.medications': 'Medications',
      'consultation.config.sections.complaints': 'Complaints',
      'consultation.config.sections.symptoms': 'Symptoms',

      // Medical Orders Configuration
      'consultation.config.medicalOrders.title': 'Medical Orders & Tests',
      'consultation.config.medicalOrders.subtitle': 'Configure laboratory tests and medical procedures',
      'consultation.config.medicalOrders.addTest': 'Add Test',
      'consultation.config.medicalOrders.addTestDescription': 'Add a new laboratory test or medical procedure',
      'consultation.config.medicalOrders.testList.title': 'Available Tests',
      'consultation.config.medicalOrders.testList.description': 'Laboratory tests and medical procedures available for ordering',
      'consultation.config.medicalOrders.status.active': 'Active',
      'consultation.config.medicalOrders.status.inactive': 'Inactive',
      'consultation.config.medicalOrders.actions.activate': 'Activate',
      'consultation.config.medicalOrders.actions.deactivate': 'Deactivate',
      'consultation.config.medicalOrders.details.preparation': 'Preparation',
      'consultation.config.medicalOrders.details.turnaround': 'Turnaround',
      'consultation.config.medicalOrders.details.cost': 'Cost',
      'consultation.config.medicalOrders.form.name': 'Test Name',
      'consultation.config.medicalOrders.form.category': 'Category',
      'consultation.config.medicalOrders.form.description': 'Description',
      'consultation.config.medicalOrders.form.preparation': 'Patient Preparation',
      'consultation.config.medicalOrders.form.turnaroundTime': 'Turnaround Time',
      'consultation.config.medicalOrders.form.cost': 'Cost',
      'consultation.config.medicalOrders.form.selectCategory': 'Select category',
      'consultation.config.medicalOrders.editTest.title': 'Edit Test',
      'consultation.config.medicalOrders.editTest.description': 'Modify test information and settings',
      'consultation.config.medicalOrders.editTest.save': 'Save Changes',

      // Medications Configuration
      'consultation.config.medications.title': 'Medications',
      'consultation.config.medications.subtitle': 'Manage medication catalog and prescribing options',
      'consultation.config.medications.addMedication': 'Add Medication',
      'consultation.config.medications.addMedicationDescription': 'Add a new medication to the catalog',
      'consultation.config.medications.medicationList.title': 'Medication Catalog',
      'consultation.config.medications.medicationList.description': 'Available medications for prescribing',
      'consultation.config.medications.status.active': 'Active',
      'consultation.config.medications.status.inactive': 'Inactive',
      'consultation.config.medications.actions.activate': 'Activate',
      'consultation.config.medications.actions.deactivate': 'Deactivate',
      'consultation.config.medications.details.forms': 'Forms',
      'consultation.config.medications.details.strengths': 'Strengths',
      'consultation.config.medications.details.indications': 'Indications',
      'consultation.config.medications.form.name': 'Medication Name',
      'consultation.config.medications.form.genericName': 'Generic Name',
      'consultation.config.medications.form.category': 'Category',
      'consultation.config.medications.form.dosageForms': 'Dosage Forms',
      'consultation.config.medications.form.strengths': 'Available Strengths',
      'consultation.config.medications.form.description': 'Description',
      'consultation.config.medications.form.indications': 'Indications',
      'consultation.config.medications.form.contraindications': 'Contraindications',
      'consultation.config.medications.form.sideEffects': 'Side Effects',
      'consultation.config.medications.form.selectCategory': 'Select category',

      // Complaints Configuration
      'consultation.config.complaints.title': 'Common Complaints',
      'consultation.config.complaints.subtitle': 'Manage patient complaint templates and categories',
      'consultation.config.complaints.addComplaint': 'Add Complaint',
      'consultation.config.complaints.addComplaintDescription': 'Add a new common complaint template',
      'consultation.config.complaints.complaintList.title': 'Complaint Templates',
      'consultation.config.complaints.complaintList.description': 'Common complaints used in consultations',
      'consultation.config.complaints.status.active': 'Active',
      'consultation.config.complaints.status.inactive': 'Inactive',
      'consultation.config.complaints.actions.activate': 'Activate',
      'consultation.config.complaints.actions.deactivate': 'Deactivate',
      'consultation.config.complaints.details.icd10': 'ICD-10',
      'consultation.config.complaints.details.symptoms': 'Common Symptoms',
      'consultation.config.complaints.form.name': 'Complaint Name',
      'consultation.config.complaints.form.category': 'Category',
      'consultation.config.complaints.form.description': 'Description',
      'consultation.config.complaints.form.icd10Code': 'ICD-10 Code',
      'consultation.config.complaints.form.severity': 'Severity',
      'consultation.config.complaints.form.commonSymptoms': 'Common Symptoms',
      'consultation.config.complaints.form.selectCategory': 'Select category',

      // Symptoms Configuration
      'consultation.config.symptoms.title': 'Symptoms',
      'consultation.config.symptoms.subtitle': 'Manage symptom definitions and associations',
      'consultation.config.symptoms.addSymptom': 'Add Symptom',
      'consultation.config.symptoms.addSymptomDescription': 'Add a new symptom definition',
      'consultation.config.symptoms.symptomList.title': 'Symptom Definitions',
      'consultation.config.symptoms.symptomList.description': 'Available symptoms for consultation documentation',
      'consultation.config.symptoms.status.active': 'Active',
      'consultation.config.symptoms.status.inactive': 'Inactive',
      'consultation.config.symptoms.actions.activate': 'Activate',
      'consultation.config.symptoms.actions.deactivate': 'Deactivate',
      'consultation.config.symptoms.details.bodySystem': 'Body System',
      'consultation.config.symptoms.details.duration': 'Duration',
      'consultation.config.symptoms.details.associatedConditions': 'Associated Conditions',
      'consultation.config.symptoms.form.name': 'Symptom Name',
      'consultation.config.symptoms.form.category': 'Category',
      'consultation.config.symptoms.form.description': 'Description',
      'consultation.config.symptoms.form.bodySystem': 'Body System',
      'consultation.config.symptoms.form.severity': 'Severity',
      'consultation.config.symptoms.form.duration': 'Duration',
      'consultation.config.symptoms.form.associatedConditions': 'Associated Conditions',
      'consultation.config.symptoms.form.selectCategory': 'Select category',
      'consultation.config.symptoms.form.selectBodySystem': 'Select body system',
      'consultation.config.symptoms.form.selectDuration': 'Select duration',

      // Tools
      'tools.title': 'Tools',
      'tools.subtitle': 'Medical configuration and management tools',
      'tools.sections.medicalOrders': 'Medical Orders',
      'tools.sections.medications': 'Medications',
      'tools.sections.complaints': 'Complaints',
      'tools.sections.symptoms': 'Symptoms',
    }
  } else {
    return {
    // Navigation
    'nav.home': 'Inicio',
    'nav.doctors': 'Nuestros Doctores',
    'nav.services': 'Servicios',
    'nav.appointments': 'Citas',
    'nav.news': 'Noticias y Actualizaciones',
    'nav.contact': 'Contáctanos',
    "nav.messages": "Mensajes",
    "nav.inventory": "Inventario",
    "nav.patients": "Pacientes",
    "nav.billing": "Facturación",
    "nav.activityLogs": "Registros de Actividad",

    // Header
    'header.title': 'Intergastro',
    'header.subtitle': 'Tu Socio de Salud',
    'header.search.placeholder': 'Buscar doctores, servicios...',
    'header.language.en': 'Switch to Spanish',
    'header.language.es': 'Cambiar a Inglés',
    
    // Hero Section
    'hero.title': 'Tu Salud, Nuestra Prioridad',
    'hero.subtitle': 'Proporcionando atención médica excepcional con compasión y experiencia. Nuestro equipo de doctores experimentados está aquí para servirte a ti y a tu familia.',
    'hero.cta.primary': 'Agendar Cita',
    'hero.cta.secondary': 'Saber Más',
    
    // Doctors Section
    'doctors.title': 'Conoce a Nuestros Doctores Expertos',
    'doctors.subtitle': 'Nuestro equipo de profesionales médicos altamente calificados está dedicado a proporcionarte la mejor atención posible.',
    'doctors.experience': 'años de experiencia',
    'doctors.book': 'Reservar Consulta',
    
    // Services Section
    'services.title': 'Nuestros Servicios Médicos',
    'services.subtitle': 'Servicios de atención médica integral adaptados para satisfacer tus necesidades médicas.',
    'services.general.title': 'Consulta General',
    'services.general.description': 'Chequeos de salud integrales y atención médica rutinaria',
    'services.cardiology.title': 'Cardiología',
    'services.cardiology.description': 'Evaluaciones de salud cardíaca y tratamientos cardiovasculares',
    'services.preventive.title': 'Cuidado Preventivo',
    'services.preventive.description': 'Vacunas, exámenes de detección y mantenimiento de la salud',
    'services.emergency.title': 'Atención de Emergencia',
    'services.emergency.description': 'Servicios médicos de emergencia y atención urgente 24/7',
    
    // News Section
    'news.title': 'Últimas Noticias y Actualizaciones',
    'news.subtitle': 'Mantente informado con las últimas perspectivas médicas y actualizaciones de la clínica de nuestros doctores.',
    'news.readMore': 'Leer Más',
    
    // Contact Section
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Ponte en contacto con nosotros para citas, consultas o atención de emergencia.',
    'contact.address.title': 'Dirección',
    'contact.address.value': 'Plaza Intermédica 3er Nivel,\n #309-C 3a Calle Poniente y 25 Avenida Norte, \n San Salvador',
    'contact.phone.title': 'Teléfono',
    'contact.phone.main': 'Principal: (503) 7777-7777',
    'contact.phone.emergency': 'Emergencia: 911',
    'contact.email.title': 'Correo Electrónico',
    'contact.email.general': 'General: info@intergastro.com',
    'contact.email.appointments': 'Citas: appointments@intergastro.com',
    'contact.hours.title': 'Horarios',
    'contact.hours.weekdays': 'Lunes - Viernes: 8:00 AM - 6:00 PM',
    'contact.hours.saturday': 'Sábado: 9:00 AM - 4:00 PM',
    'contact.hours.sunday': 'Domingo: Solo Emergencias',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.firstName': 'Nombre',
    'contact.form.lastName': 'Apellido',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.phone': 'Teléfono',
    'contact.form.message': 'Tu mensaje...',
    'contact.form.send': 'Enviar Mensaje',
    
    // Footer
    'footer.copyright': '© 2024 Intergastro. Todos los derechos reservados. | Proveedor de Salud Licenciado',
    
    // Quick Contact
    'quick.contact.phone': '(503) 7777-7777',
    'quick.contact.email': 'info@intergastro.com',
    'quick.contact.hours': 'Lun-Vie: 8AM-6PM',

      // Settings
      'settings.title': 'Configuraciones',
      'settings.subtitle': 'Administra las preferencias y ajustes de la clínica',
      'settings.sections.clinic': 'Perfil de la Clínica',
      'settings.sections.users': 'Usuarios y Roles',
      'settings.sections.schedule': 'Agenda y Horarios',
      'settings.sections.billing': 'Facturación y DTE',
      'settings.sections.notifications': 'Notificaciones',
      'settings.sections.security': 'Seguridad',
      'settings.sections.integrations': 'Integraciones',

      // Clinic Profile
      'settings.clinic.title': 'Perfil de la Clínica',
      'settings.clinic.subtitle': 'Información básica de la clínica médica',
      'settings.clinic.general.title': 'Información General',
      'settings.clinic.general.description': 'Datos principales de la clínica',
      'settings.clinic.general.name': 'Nombre de la Clínica',
      'settings.clinic.general.namePlaceholder': 'Clínica Médica San Rafael',
      'settings.clinic.general.phone': 'Teléfono',
      'settings.clinic.general.phonePlaceholder': '+503 2234-5678',
      'settings.clinic.general.address': 'Dirección',
      'settings.clinic.general.addressPlaceholder': 'Av. Principal #123, San Salvador, El Salvador',
      'settings.clinic.general.email': 'Correo Electrónico',
      'settings.clinic.general.emailPlaceholder': 'info@clinicasanrafael.com',
      'settings.clinic.general.logo': 'Logo de la Clínica',
      'settings.clinic.general.uploadLogo': 'Subir Logo',
      'settings.clinic.general.specialties': 'Especialidades Médicas',
      'settings.clinic.general.specialty.general': 'Medicina General',
      'settings.clinic.general.specialty.cardiology': 'Cardiología',
      'settings.clinic.general.specialty.pediatrics': 'Pediatría',
      'settings.clinic.general.addSpecialty': 'Agregar',
      'settings.clinic.general.language': 'Idioma',
      'settings.clinic.general.selectLanguage': 'Seleccionar idioma',
      'settings.clinic.general.language.es': 'Español',
      'settings.clinic.general.language.en': 'English',
      'settings.clinic.general.timezone': 'Zona Horaria',
      'settings.clinic.general.selectTimezone': 'Seleccionar zona horaria',
      'settings.clinic.general.timezone.elSalvador': 'América/El Salvador (CST)',
      'settings.clinic.general.timezone.guatemala': 'América/Guatemala (CST)',
      'settings.clinic.saveChanges': 'Guardar Cambios',

      // Users & Roles
      'settings.users.title': 'Usuarios y Roles',
      'settings.users.subtitle': 'Gestiona los usuarios y sus permisos',
      'settings.users.addUser': 'Agregar Usuario',
      'settings.users.addUserDescription': 'Crea una nueva cuenta de usuario con un rol y permisos específicos',
      'settings.users.editUser.title': 'Editar Usuario',
      'settings.users.editUser.description': 'Modifica la información del usuario y su rol',
      'settings.users.editUser.save': 'Guardar Cambios',
      'settings.users.passwordReset.title': 'Restablecer Contraseña',
      'settings.users.passwordReset.description': 'Establece una nueva contraseña para',
      'settings.users.passwordReset.newPassword': 'Nueva Contraseña',
      'settings.users.passwordReset.reset': 'Restablecer Contraseña',
      'settings.users.deleteUser.title': 'Eliminar Usuario',
      'settings.users.deleteUser.description': '¿Estás seguro de que quieres eliminar',
      'settings.users.deleteUser.cancel': 'Cancelar',
      'settings.users.deleteUser.confirm': 'Eliminar',
      'settings.users.lastLogin': 'Último Inicio de Sesión',
      'settings.users.form.name': 'Nombre',
      'settings.users.form.email': 'Correo Electrónico',
      'settings.users.form.roles': 'Roles',
      'settings.users.form.selectRole': 'Seleccionar rol',
      'settings.users.form.password': 'Contraseña',
      'settings.users.form.status': 'Estado',
      'settings.users.status.active': 'Activo',
      'settings.users.status.inactive': 'Inactivo',
      'settings.users.userList.title': 'Lista de Usuarios',
      'settings.users.userList.description': 'Usuarios registrados en el sistema',
      'settings.users.userList.doctor1.name': 'Dr. Roberto Martínez',
      'settings.users.userList.doctor1.email': 'roberto@clinica.com',
      'settings.users.userList.doctor1.role': 'Administrador',
      'settings.users.userList.doctor2.name': 'Dra. María González',
      'settings.users.userList.doctor2.email': 'maria@clinica.com',
      'settings.users.userList.doctor2.role': 'Doctor',
      'settings.users.userList.secretary.name': 'Ana Rodríguez',
      'settings.users.userList.secretary.email': 'ana@clinica.com',
      'settings.users.userList.secretary.role': 'Secretaria',
      'settings.users.roles.title': 'Configuración de Roles',
      'settings.users.roles.description': 'Define los permisos para cada rol',
      'settings.users.roles.admin.title': 'Permisos del Administrador',
      'settings.users.roles.admin.manageUsers': 'Gestionar usuarios',
      'settings.users.roles.admin.billingAccess': 'Acceso a facturación',
      'settings.users.roles.admin.viewReports': 'Ver reportes',
      'settings.users.roles.admin.settings': 'Configuraciones',
      'settings.users.roles.doctor.title': 'Permisos del Doctor',
      'settings.users.roles.doctor.managePatients': 'Gestionar pacientes',
      'settings.users.roles.doctor.viewAppointments': 'Ver citas',
      'settings.users.roles.doctor.prescribeMedications': 'Recetar medicamentos',
      'settings.users.roles.doctor.viewMedicalReports': 'Ver reportes médicos',
      'settings.users.roles.secretary.title': 'Secretaria',
      'settings.users.roles.secretary.viewPatients': 'Ver pacientes',
      'settings.users.roles.secretary.manageAppointments': 'Gestionar citas',
      'settings.users.roles.secretary.viewBilling': 'Ver facturación',
      'settings.users.roles.secretary.viewBasicReports': 'Ver reportes básicos',
      'settings.users.roles.secretary.phoneAccess': 'Acceso al teléfono',
      'settings.users.roles.secretary.emailAccess': 'Acceso al correo electrónico',

      // Schedule
      'settings.schedule.title': 'Agenda y Horarios',
      'settings.schedule.subtitle': 'Configura los horarios de atención y citas',
      'settings.schedule.hours.title': 'Horarios de Atención',
      'settings.schedule.hours.description': 'Define los horarios por día de la semana',
      'settings.schedule.hours.days.monday': 'Lunes',
      'settings.schedule.hours.days.tuesday': 'Martes',
      'settings.schedule.hours.days.wednesday': 'Miércoles',
      'settings.schedule.hours.days.thursday': 'Jueves',
      'settings.schedule.hours.days.friday': 'Viernes',
      'settings.schedule.hours.days.saturday': 'Sábado',
      'settings.schedule.hours.days.sunday': 'Domingo',
      'settings.schedule.hours.to': 'a',
      'settings.schedule.appointments.title': 'Configuración de Citas',
      'settings.schedule.appointments.description': 'Parámetros para el sistema de citas',
      'settings.schedule.appointments.duration': 'Duración estándar de cita',
      'settings.schedule.appointments.selectDuration': 'Seleccionar duración',
      'settings.schedule.appointments.duration.15min': '15 minutos',
      'settings.schedule.appointments.duration.30min': '30 minutos',
      'settings.schedule.appointments.duration.45min': '45 minutos',
      'settings.schedule.appointments.duration.1hour': '1 hora',
      'settings.schedule.appointments.bufferTime': 'Tiempo de buffer entre citas',
      'settings.schedule.appointments.selectBuffer': 'Seleccionar buffer',
      'settings.schedule.appointments.buffer.noBuffer': 'Sin buffer',
      'settings.schedule.appointments.buffer.5min': '5 minutos',
      'settings.schedule.appointments.buffer.10min': '10 minutos',
      'settings.schedule.appointments.buffer.15min': '15 minutos',
      'settings.schedule.appointments.holidays': 'Días feriados y excepciones',
      'settings.schedule.appointments.holidays.newYear': '1 de Enero - Año Nuevo',
      'settings.schedule.appointments.holidays.independence': '15 de Septiembre - Independencia',
      'settings.schedule.appointments.holidays.addHoliday': 'Agregar Feriado',

      // Billing
      'settings.billing.title': 'Facturación y DTE',
      'settings.billing.subtitle': 'Configuración fiscal y de facturación electrónica',
      'settings.billing.tax.title': 'Datos Fiscales',
      'settings.billing.tax.description': 'Información fiscal de la clínica',
      'settings.billing.tax.nit': 'NIT',
      'settings.billing.tax.nitPlaceholder': '0614-123456-123-4',
      'settings.billing.tax.businessName': 'Razón Social',
      'settings.billing.tax.businessNamePlaceholder': 'Clínica Médica San Rafael S.A. de C.V.',
      'settings.billing.tax.taxAddress': 'Dirección Fiscal',
      'settings.billing.tax.taxAddressPlaceholder': 'Dirección registrada en el NIT',
      'settings.billing.tax.currency': 'Moneda',
      'settings.billing.tax.selectCurrency': 'Seleccionar moneda',
      'settings.billing.tax.currency.usd': 'USD - Dólar Americano',
      'settings.billing.tax.currency.eur': 'EUR - Euro',
      'settings.billing.tax.vatRate': 'Tasa de IVA (%)',
      'settings.billing.dte.title': 'Facturación Electrónica (DTE)',
      'settings.billing.dte.description': 'Configuración para el sistema de DTE de El Salvador',
      'settings.billing.dte.enable': 'Habilitar DTE',
      'settings.billing.dte.enableDescription': 'Activar facturación electrónica',
      'settings.billing.dte.environment': 'Ambiente',
      'settings.billing.dte.selectEnvironment': 'Seleccionar ambiente',
      'settings.billing.dte.environment.test': 'Pruebas',
      'settings.billing.dte.environment.production': 'Producción',
      'settings.billing.dte.invoiceSeries': 'Serie de Facturas',
      'settings.billing.dte.nextInvoiceNumber': 'Próximo Número de Factura',

      // Notifications
      'settings.notifications.title': 'Notificaciones',
      'settings.notifications.subtitle': 'Configura las notificaciones automáticas',
      'settings.notifications.email.title': 'Notificaciones por Email',
      'settings.notifications.email.description': 'Configuración de correos automáticos',
      'settings.notifications.email.confirmations': 'Confirmaciones de cita',
      'settings.notifications.email.confirmationsDescription': 'Enviar email al confirmar citas',
      'settings.notifications.email.reminders': 'Recordatorios de cita',
      'settings.notifications.email.remindersDescription': 'Recordatorio 24h antes de la cita',
      'settings.notifications.email.invoices': 'Facturas emitidas',
      'settings.notifications.email.invoicesDescription': 'Enviar factura por email',
      'settings.notifications.sms.title': 'Notificaciones por SMS',
      'settings.notifications.sms.description': 'Configuración de mensajes de texto',
      'settings.notifications.sms.reminders': 'Recordatorios por SMS',
      'settings.notifications.sms.remindersDescription': 'SMS 2 horas antes de la cita',
      'settings.notifications.sms.confirmations': 'Confirmaciones por SMS',
      'settings.notifications.sms.confirmationsDescription': 'SMS al agendar cita',
      'settings.notifications.templates.title': 'Plantillas de Mensajes',
      'settings.notifications.templates.description': 'Personaliza los mensajes automáticos',
      'settings.notifications.templates.reminder': 'Plantilla de Recordatorio',
      'settings.notifications.templates.reminderPlaceholder': 'Hola {nombre}, te recordamos tu cita el {fecha} a las {hora} en {clinica}.',
      'settings.notifications.templates.confirmation': 'Plantilla de Confirmación',
      'settings.notifications.templates.confirmationPlaceholder': 'Tu cita ha sido confirmada para el {fecha} a las {hora}. Gracias por elegir {clinica}.',

      // Security
      'settings.security.title': 'Seguridad',
      'settings.security.subtitle': 'Configuración de seguridad y acceso',
      'settings.security.password.title': 'Cambio de Contraseña',
      'settings.security.password.description': 'Actualiza tu contraseña de acceso',
      'settings.security.password.current': 'Contraseña Actual',
      'settings.security.password.new': 'Nueva Contraseña',
      'settings.security.password.confirm': 'Confirmar Nueva Contraseña',
      'settings.security.password.change': 'Cambiar Contraseña',
      'settings.security.2fa.title': 'Autenticación de Dos Factores (2FA)',
      'settings.security.2fa.description': 'Añade una capa extra de seguridad',
      'settings.security.2fa.enable': 'Habilitar 2FA',
      'settings.security.2fa.enableDescription': 'Requiere código adicional al iniciar sesión',
      'settings.security.2fa.method': 'Método de 2FA',
      'settings.security.2fa.selectMethod': 'Seleccionar método',
      'settings.security.2fa.method.sms': 'SMS',
      'settings.security.2fa.method.email': 'Email',
      'settings.security.2fa.method.app': 'App Autenticadora',
      'settings.security.sessions.title': 'Sesiones Activas',
      'settings.security.sessions.description': 'Dispositivos con sesión iniciada',
      'settings.security.sessions.chromeWindows': 'Chrome en Windows',
      'settings.security.sessions.chromeWindowsDetails': 'IP: 192.168.1.100 • Última actividad: Hace 5 min',
      'settings.security.sessions.safariIphone': 'Safari en iPhone',
      'settings.security.sessions.safariIphoneDetails': 'IP: 192.168.1.105 • Última actividad: Hace 2 horas',
      'settings.security.sessions.current': 'Actual',
      'settings.security.sessions.logout': 'Cerrar Sesión',
      'settings.security.sessions.logoutAll': 'Cerrar Todas las Sesiones',
      'settings.security.policies.title': 'Políticas de Contraseñas',
      'settings.security.policies.description': 'Requisitos para contraseñas de usuarios',
      'settings.security.policies.minLength': 'Longitud mínima',
      'settings.security.policies.expiryDays': 'Caducidad (días)',
      'settings.security.policies.requireUppercase': 'Requiere mayúsculas',
      'settings.security.policies.requireNumbers': 'Requiere números',
      'settings.security.policies.requireSymbols': 'Requiere símbolos',

      // Integrations
      'settings.integrations.title': 'Integraciones',
      'settings.integrations.subtitle': 'Conecta con sistemas externos',
      'settings.integrations.payments.title': 'Pagos',
      'settings.integrations.payments.description': 'Procesadores de pagos en línea',
      'settings.integrations.payments.stripe.name': 'Stripe',
      'settings.integrations.payments.stripe.description': 'Procesamiento de tarjetas',
      'settings.integrations.payments.paypal.name': 'PayPal',
      'settings.integrations.payments.paypal.description': 'Pagos digitales',
      'settings.integrations.calendar.title': 'Calendario',
      'settings.integrations.calendar.description': 'Sincronización de citas',
      'settings.integrations.calendar.google.name': 'Google Calendar',
      'settings.integrations.calendar.google.description': 'Sincronizar citas médicas',
      'settings.integrations.calendar.outlook.name': 'Outlook Calendar',
      'settings.integrations.calendar.outlook.description': 'Integración con Microsoft',
      'settings.integrations.laboratories.title': 'Laboratorios',
      'settings.integrations.laboratories.description': 'Sistemas de laboratorio clínico',
      'settings.integrations.laboratories.labcorp.name': 'LabCorp',
      'settings.integrations.laboratories.labcorp.description': 'Resultados de laboratorio',
      'settings.integrations.ai.title': 'Inteligencia Artificial',
      'settings.integrations.ai.description': 'Servicios de AI médica',
      'settings.integrations.ai.transcription.name': 'AI Transcription',
      'settings.integrations.ai.transcription.description': 'Transcripción de consultas',
      'settings.integrations.ai.diagnosis.name': 'AI Diagnosis Assistant',
      'settings.integrations.ai.diagnosis.description': 'Asistente de diagnóstico',
      'settings.integrations.status.connected': 'Conectado',
      'settings.integrations.status.disconnected': 'Desconectado',
      'settings.integrations.connect': 'Conectar',
      'settings.integrations.configure': 'Configurar',

      // Messages
      'messages.title': 'Envíos del Formulario de Contacto',
      'messages.subtitle': 'Gestiona y revisa las consultas y solicitudes de contacto de los pacientes',
      'messages.search.placeholder': 'Buscar por nombre, email o mensaje...',
      'messages.filter.all': 'Todos los Mensajes',
      'messages.filter.new': 'Solo Nuevos',
      'messages.filter.reviewed': 'Solo Revisados',
      'messages.status.new': 'Nuevo',
      'messages.status.reviewed': 'Revisado',
      'messages.sections.new': 'Mensajes Nuevos',
      'messages.sections.reviewed': 'Mensajes Revisados',
      'messages.actions.viewDetails': 'Ver Detalles',
      'messages.actions.markReviewed': 'Marcar Revisado',
      'messages.noResults': 'No se encontraron mensajes que coincidan con tus criterios.',
      'messages.clearFilters': 'Limpiar Filtros',
      'messages.modal.title': 'Detalles del Mensaje',
      'messages.modal.contact.email': 'Correo:',
      'messages.modal.contact.phone': 'Teléfono:',
      'messages.modal.message': 'Mensaje:',
      'messages.dateFormat.short': 'corta',
      'messages.dateFormat.long': 'larga',
      'messages.placeholder.noMessage': 'Sin mensaje',
      'messages.placeholder.noEmail': 'Sin correo',
      'messages.placeholder.noPhone': 'Sin teléfono',

      // Consultation Configuration
      'consultation.config.title': 'Configuración de Consultas',
      'consultation.config.subtitle': 'Gestiona órdenes médicas, medicamentos, quejas y síntomas',
      'consultation.config.sections.medicalOrders': 'Órdenes Médicas',
      'consultation.config.sections.medications': 'Medicamentos',
      'consultation.config.sections.complaints': 'Quejas',
      'consultation.config.sections.symptoms': 'Síntomas',

      // Medical Orders Configuration
      'consultation.config.medicalOrders.title': 'Órdenes Médicas y Exámenes',
      'consultation.config.medicalOrders.subtitle': 'Configura exámenes de laboratorio y procedimientos médicos',
      'consultation.config.medicalOrders.addTest': 'Agregar Examen',
      'consultation.config.medicalOrders.addTestDescription': 'Agregar un nuevo examen de laboratorio o procedimiento médico',
      'consultation.config.medicalOrders.testList.title': 'Exámenes Disponibles',
      'consultation.config.medicalOrders.testList.description': 'Exámenes de laboratorio y procedimientos médicos disponibles para ordenar',
      'consultation.config.medicalOrders.status.active': 'Activo',
      'consultation.config.medicalOrders.status.inactive': 'Inactivo',
      'consultation.config.medicalOrders.actions.activate': 'Activar',
      'consultation.config.medicalOrders.actions.deactivate': 'Desactivar',
      'consultation.config.medicalOrders.details.preparation': 'Preparación',
      'consultation.config.medicalOrders.details.turnaround': 'Tiempo de Respuesta',
      'consultation.config.medicalOrders.details.cost': 'Costo',
      'consultation.config.medicalOrders.form.name': 'Nombre del Examen',
      'consultation.config.medicalOrders.form.category': 'Categoría',
      'consultation.config.medicalOrders.form.description': 'Descripción',
      'consultation.config.medicalOrders.form.preparation': 'Preparación del Paciente',
      'consultation.config.medicalOrders.form.turnaroundTime': 'Tiempo de Respuesta',
      'consultation.config.medicalOrders.form.cost': 'Costo',
      'consultation.config.medicalOrders.form.selectCategory': 'Seleccionar categoría',
      'consultation.config.medicalOrders.editTest.title': 'Editar Examen',
      'consultation.config.medicalOrders.editTest.description': 'Modificar información y configuración del examen',
      'consultation.config.medicalOrders.editTest.save': 'Guardar Cambios',

      // Medications Configuration
      'consultation.config.medications.title': 'Medicamentos',
      'consultation.config.medications.subtitle': 'Gestiona el catálogo de medicamentos y opciones de prescripción',
      'consultation.config.medications.addMedication': 'Agregar Medicamento',
      'consultation.config.medications.addMedicationDescription': 'Agregar un nuevo medicamento al catálogo',
      'consultation.config.medications.medicationList.title': 'Catálogo de Medicamentos',
      'consultation.config.medications.medicationList.description': 'Medicamentos disponibles para prescribir',
      'consultation.config.medications.status.active': 'Activo',
      'consultation.config.medications.status.inactive': 'Inactivo',
      'consultation.config.medications.actions.activate': 'Activar',
      'consultation.config.medications.actions.deactivate': 'Desactivar',
      'consultation.config.medications.details.forms': 'Formas',
      'consultation.config.medications.details.strengths': 'Concentraciones',
      'consultation.config.medications.details.indications': 'Indicaciones',
      'consultation.config.medications.form.name': 'Nombre del Medicamento',
      'consultation.config.medications.form.genericName': 'Nombre Genérico',
      'consultation.config.medications.form.category': 'Categoría',
      'consultation.config.medications.form.dosageForms': 'Formas de Dosificación',
      'consultation.config.medications.form.strengths': 'Concentraciones Disponibles',
      'consultation.config.medications.form.description': 'Descripción',
      'consultation.config.medications.form.indications': 'Indicaciones',
      'consultation.config.medications.form.contraindications': 'Contraindicaciones',
      'consultation.config.medications.form.sideEffects': 'Efectos Secundarios',
      'consultation.config.medications.form.selectCategory': 'Seleccionar categoría',

      // Complaints Configuration
      'consultation.config.complaints.title': 'Quejas Comunes',
      'consultation.config.complaints.subtitle': 'Gestiona plantillas de quejas de pacientes y categorías',
      'consultation.config.complaints.addComplaint': 'Agregar Queja',
      'consultation.config.complaints.addComplaintDescription': 'Agregar una nueva plantilla de queja común',
      'consultation.config.complaints.complaintList.title': 'Plantillas de Quejas',
      'consultation.config.complaints.complaintList.description': 'Quejas comunes utilizadas en consultas',
      'consultation.config.complaints.status.active': 'Activo',
      'consultation.config.complaints.status.inactive': 'Inactivo',
      'consultation.config.complaints.actions.activate': 'Activar',
      'consultation.config.complaints.actions.deactivate': 'Desactivar',
      'consultation.config.complaints.details.icd10': 'Código ICD-10',
      'consultation.config.complaints.details.symptoms': 'Síntomas Comunes',
      'consultation.config.complaints.form.name': 'Nombre de la Queja',
      'consultation.config.complaints.form.category': 'Categoría',
      'consultation.config.complaints.form.description': 'Descripción',
      'consultation.config.complaints.form.icd10Code': 'Código ICD-10',
      'consultation.config.complaints.form.severity': 'Severidad',
      'consultation.config.complaints.form.commonSymptoms': 'Síntomas Comunes',
      'consultation.config.complaints.form.selectCategory': 'Seleccionar categoría',

      // Symptoms Configuration
      'consultation.config.symptoms.title': 'Síntomas',
      'consultation.config.symptoms.subtitle': 'Gestiona definiciones de síntomas y asociaciones',
      'consultation.config.symptoms.addSymptom': 'Agregar Síntoma',
      'consultation.config.symptoms.addSymptomDescription': 'Agregar una nueva definición de síntoma',
      'consultation.config.symptoms.symptomList.title': 'Definiciones de Síntomas',
      'consultation.config.symptoms.symptomList.description': 'Síntomas disponibles para documentación de consultas',
      'consultation.config.symptoms.status.active': 'Activo',
      'consultation.config.symptoms.status.inactive': 'Inactivo',
      'consultation.config.symptoms.actions.activate': 'Activar',
      'consultation.config.symptoms.actions.deactivate': 'Desactivar',
      'consultation.config.symptoms.details.bodySystem': 'Sistema del Cuerpo',
      'consultation.config.symptoms.details.duration': 'Duración',
      'consultation.config.symptoms.details.associatedConditions': 'Condiciones Asociadas',
      'consultation.config.symptoms.form.name': 'Nombre del Síntoma',
      'consultation.config.symptoms.form.category': 'Categoría',
      'consultation.config.symptoms.form.description': 'Descripción',
      'consultation.config.symptoms.form.bodySystem': 'Sistema del Cuerpo',
      'consultation.config.symptoms.form.severity': 'Severidad',
      'consultation.config.symptoms.form.duration': 'Duración',
      'consultation.config.symptoms.form.associatedConditions': 'Condiciones Asociadas',
      'consultation.config.symptoms.form.selectCategory': 'Seleccionar categoría',
      'consultation.config.symptoms.form.selectBodySystem': 'Seleccionar sistema del cuerpo',
      'consultation.config.symptoms.form.selectDuration': 'Seleccionar duración',

      // Tools
      'tools.title': 'Herramientas',
      'tools.subtitle': 'Herramientas de configuración y gestión médica',
      'tools.sections.medicalOrders': 'Órdenes Médicas',
      'tools.sections.medications': 'Medicamentos',
      'tools.sections.complaints': 'Quejas',
      'tools.sections.symptoms': 'Síntomas',


    }
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es')) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when it changes
  const handleLanguageChange = useCallback((lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }, [])

  // Memoize translations to prevent unnecessary re-renders
  const translations = useMemo(() => getTranslations(language), [language])

  // Translation function with memoization
  const t = useCallback((key: string): string => {
    return translations[key as keyof typeof translations] || key
  }, [translations])

  const contextValue = useMemo(() => ({
      language, 
      setLanguage: handleLanguageChange, 
      t 
  }), [language, handleLanguageChange, t])

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
